version: "3"
services:
  python:
    build:
      context: ../
      dockerfile: ./todo_eric/docker/Dockerfile
    ports:
      ["8000:8000"]
    volumes:
      ["./app:/todo_eric"]
    depends_on:
      ["db"]
  db:
    image: postgres
