# Generated by Django 2.1.7 on 2019-02-24 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_lista_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista',
            name='usuario',
            field=models.ForeignKey(default=1, max_length=50, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
